### ISSUE TITLE
Comments are not using the default font defined in settings

### ISSUE THREAD

**Issue by dkast** [Yummygum/city-lights-syntax-atom#1]
Hi guys!
For some reason, the comments on the atom syntax are not using the default monospaced font that was defined on the settings view. I also tested using the default font with the same results.

![image](https://user-images.githubusercontent.com/3997998/32397701-23da6d36-c0b9-11e7-8aca-99b53dead58e.png)

**OS:** Windows 10
**Atom version:** 1.21.2

**Comment by alexesprit** [comment]
Have the same issue.

Btw, I changed comment font by adding this code in my `styles.less`:
```less
// Syntax styles
.syntax--comment {
  font-family: '%your_font_name%' !important;
}
```

**Comment by victorhqc** [comment]
Happening the same to me. Opened a PR to address this

**Comment by noudadrichem** [comment]
I patched this, update in Atom and let me hear if it's fixed (or not).😊

**Comment by dkast** [comment]
The issue persist on ver. 1.1.1 on Win 10, I believe is related to the `font-family` definition for the comments, that is using Monaco as defautl font. That font does not exist as a system font on Win 10.
https://github.com/Yummygum/city-lights-syntax-atom/blob/5875078d6efb41284d032d1edd1e4ad5ba2576cf/styles/base.less#L102

If I comment the line and reload the theme, the comments seems to display correctly. I can open a PR but I don't have a way to test this change on macOS right now 😕

![image](https://user-images.githubusercontent.com/3997998/32472462-72fd4f20-c328-11e7-99dc-6dfc2a7b9109.png)

**Comment by victorhqc** [comment]
You're right. Current way to workaround it still is by adding
```less
atom-text-editor.editor {
    .syntax--comment {
        font-family: "your-font";
    }
}
```
In Atom's stylesheet
