### ISSUE TITLE
Comments spacing issue

### ISSUE THREAD

**Issue by michaelaguiar** [Yummygum/city-lights-syntax-atom#2]
Comments formatted as // Comment have an extra space, and the tab lines are broken.

Example attached!
![screenshot 2017-11-05 19 50 00](https://user-images.githubusercontent.com/138890/32423253-8d95e5de-c262-11e7-98b0-a9cf3bcd1c4b.png)

**Comment by victorhqc** [comment]
Looks like this piece of code is breaking it:
https://github.com/Yummygum/city-lights-syntax-atom/blob/d81d6605a29662b82153226653af257ccfcb0dc2/styles/base.less#L102

A workaround for now is to edit the Atom's `.stylesheet.less` with the following
```less
atom-text-editor.editor {
    .syntax--comment {
        font-family: "Your current font" !important;
    }
}
```

**Comment by iduuck** [comment]
An even easier workaround is appending this one-liner to your custom styles.less:

```css
.syntax--comment { font-family: inherit !important; }
```

As far as I know, it is not necessary to scope a css class with this one anymore since you added the `syntax--` prefix.

---

Also flexible and future proof.

**Comment by michaelaguiar** [comment]
Beautiful.  Thanks!

**Comment by michaelaguiar** [comment]
So this is still an issue.  I can, of course add the following to my Atom stylesheet to fix, but without it, it's still broken.  I do have the latest update that was just released too.

```css
.syntax--comment { font-family: inherit !important; }
```
